spring.application.name=image-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/image-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.instance.hostname=${spring.application.name}
#eureka.instance.prefer-ip-address=false
#eureka.instance.instance-id=${spring.application.name}:${random.value}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${IMAGE_SERVICE_DB_URL}
spring.datasource.username=${IMAGE_SERVICE_DB_USER}
spring.datasource.password=${IMAGE_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

gateway.url=${GATEWAY_URL}