spring.application.name=order-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/order-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

management.tracing.enabled=true
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

gateway.url=${GATEWAY_URL}
