export const mockProducts = [
    {
        id: "prod-1",
        name: "Cơm gà xối mỡ",
        slug: "com-ga-xoi-mo",
        description: "Phần cơm gà xối mỡ giòn rụm, nước mắm chua ngọt.",
        price: 45000,
        salePrice: 40000,
        imageUrl: "/images/mock/com-ga-xoi-mo.jpg",
        isAvailable: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        restaurantId: "rest-1",
        categoryId: "cate-1",
    },
    {
        id: "prod-2",
        name: "Trà sữa trân châu đường đen",
        slug: "tra-sua-tran-chau-duong-den",
        description: "Ly trà sữa trân châu đường đen size lớn.",
        price: 35000,
        salePrice: 32000,
        imageUrl: "/images/mock/tra-sua-tran-chau-duong-den.jpg",
        isAvailable: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        restaurantId: "rest-2",
        categoryId: "cate-2",
    },
];

