export const mockRestaurants = [
    {
        id: "rest-1",
        name: "Quán Cơm Sinh Viên UIT",
        slug: "quan-com-sinh-vien-uit",
        description: "Quán cơm bình dân dành cho sinh viên, giá rẻ mà ngon.",
        address: "Khu vực ĐHQG, Thủ Đức, TP. HCM",
        openTime: "08:00",
        closeTime: "21:00",
        rating: 4.5,
        reviewCount: 128,
        imageUrl: "/images/mock/quan-com-sinh-vien-uit.jpg",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: "rest-2",
        name: "Trà Sữa 24/7",
        slug: "tra-sua-24-7",
        description: "Trà sữa cho những đêm code deadline.",
        address: "KTX Khu B, ĐHQG",
        openTime: "09:00",
        closeTime: "23:59",
        rating: 4.8,
        reviewCount: 256,
        imageUrl: "/images/mock/tra-sua-24-7.jpg",
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

