spring.application.name=blog-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/blog-service
springdoc.swagger-ui.enabled=false
springdoc.info.title=Blog Service API
springdoc.info.description=API documentation for Blog Service
springdoc.info.version=1.0.0
springdoc.info.contact.name=Tri

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.instance.hostname=${spring.application.name}
#eureka.instance.prefer-ip-address=false
#eureka.instance.instance-id=${spring.application.name}:${random.value}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

# Actuator with prometheus
management.metrics.export.prometheus.enabled=true

spring.datasource.url=${BLOG_SERVICE_DB_URL}
spring.datasource.username=${BLOG_SERVICE_DB_USER}
spring.datasource.password=${BLOG_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

gateway.url=${GATEWAY_URL}