services:
    rabbitmq:
        image: "rabbitmq:3-management"
        env_file:
            - ./.env
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    redis:
        image: "redis:7-alpine"
        container_name: redis
        env_file:
            - ./.env
        command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 3
            retries: 5
            start_period: 10s
    postgres:
        image: postgis/postgis:16-3.4 # PostgreSQL + PostGIS
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./seed-db/seed-db.sh:/docker-entrypoint-initdb.d/00_seed_db.sh
            - ./seed-db/user_service.sql:/docker-entrypoint-initdb.d/user_service.sql
            - ./seed-db/blog_service.sql:/docker-entrypoint-initdb.d/blog_service.sql
            - ./seed-db/chat_service.sql:/docker-entrypoint-initdb.d/chat_service.sql
            - ./seed-db/payment_service.sql:/docker-entrypoint-initdb.d/payment_service.sql
            - ./seed-db/restaurant_service.sql:/docker-entrypoint-initdb.d/restaurant_service.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 60s
    zipkin:
        image: openzipkin/zipkin
        expose:
            - "9411"
    keycloak:
        image: quay.io/keycloak/keycloak:24.0.0
        #override entrypoint để chạy script init.sh
        entrypoint: ["/bin/bash"]
        command: ["/tmp/init-keycloak.sh"]
        env_file:
            - ./.env
        environment:
            - KC_DB=postgres
            - KC_HEALTH_ENABLED=true
            - KC_METRICS_ENABLED=true
            - KC_HTTP_PORT=9091
            - KC_HOSTNAME=localhost
            - KC_HOSTNAME_PATH=/auth
            - KC_PROXY=edge
            - KC_HTTP_RELATIVE_PATH=/auth
        volumes:
            - ./realm.json:/tmp/realm.json:ro
            - ./init-keycloak.sh:/tmp/init-keycloak.sh:ro
            - ./themes:/opt/keycloak/themes
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_healthy
    prometheus:
        image: prom/prometheus:latest
        container_name: "prometheus"
        restart: "unless-stopped"
        expose:
            - "9090"
        volumes:
            - ./monitoring:/etc/prometheus
            - prometheus-data:/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
    grafana:
        image: grafana/grafana:latest
        environment:
            - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/monitoring
            - GF_SERVER_SERVE_FROM_SUB_PATH=true
        env_file:
            - ./.env
        container_name: grafana
        restart: "unless-stopped"
        expose:
            - "3000"
        volumes:
            - grafana-data:/var/lib/grafana #Lưu dashboard lại khi restart container
            - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
        depends_on:
            - prometheus
        healthcheck:
            test: ["CMD", "nc", "-z", "localhost", "3000"]
    caddy:
        image: caddy:2-alpine
        container_name: caddy
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - api-gateway
            - frontend
            - keycloak
            - grafana
    service-discovery:
        image: ghcr.io/buihuy13/service-discovery:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${SERVICE_DISCOVERY_PORT}
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health | grep UP || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 60s
    api-gateway:
        image: ghcr.io/buihuy13/api-gateway:${VERSION}
        expose:
            - "8080"
        env_file:
            - ./.env
        environment:
            - PORT=${API_GATEWAY_PORT}
        depends_on:
            service-discovery:
                condition: service_started
    user-service:
        image: ghcr.io/buihuy13/user-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${USER_PORT}
        depends_on:
            postgres:
                condition: service_healthy
            service-discovery:
                condition: service_started
    notification-service:
        image: ghcr.io/buihuy13/notification-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${NOTIFICATION_PORT}
            - PASSWORD=${SMTP_PASSWORD}
        depends_on:
            service-discovery:
                condition: service_started
    chat-service:
        image: ghcr.io/buihuy13/chat-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${CHAT_PORT}
        depends_on:
            postgres:
                condition: service_healthy
            service-discovery:
                condition: service_started
            redis:
                condition: service_healthy
    recommendation-service:
        image: ghcr.io/buihuy13/recommendation-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${RECOMMENDATION_PORT}
        depends_on:
            service-discovery:
                condition: service_started
    dashboard-service:
        image: ghcr.io/buihuy13/dashboard-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${DASHBOARD_PORT}
        depends_on:
            service-discovery:
                condition: service_started
    restaurant-service:
        image: ghcr.io/buihuy13/restaurant-service:${VERSION}
        env_file:
            - ./.env
        environment:
            - PORT=${RESTAURANT_PORT}
        depends_on:
            postgres:
                condition: service_healthy
            service-discovery:
                condition: service_started
    frontend:
        expose:
            - "3000"
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
                NEXT_PUBLIC_BACKEND_ORIGIN: ${NEXT_PUBLIC_BACKEND_ORIGIN}
        container_name: frontend
        env_file:
            - ./.env
        restart: unless-stopped

volumes:
    postgres_data:
    grafana-data:
    prometheus-data:
    caddy_data:
    caddy_config:
