spring.application.name=product-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/product-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties],optional:classpath:resilience4j.properties

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

#Zipkin
management.tracing.enabled=true
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${PRODUCT_SERVICE_DB_URL}
spring.datasource.username=${PRODUCT_SERVICE_DB_USER}
spring.datasource.password=${PRODUCT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#rabbitmq config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

gateway.url=${GATEWAY_URL}
