spring.application.name=query-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/query-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

#Zipkin
management.tracing.enabled=true
management.endpoints.web.exposure.include=*
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${QUERY_SERVICE_DB_URL}
spring.datasource.username=${QUERY_SERVICE_DB_USER}
spring.datasource.password=${QUERY_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#OpenRouteService
openrouteservice.api-key=${OPENROUTESERVICE_API_KEY}
openrouteservice.list-url=${OPENROUTESERVICE_LIST_URL}
openrouteservice.url=${OPENROUTESERVICE_URL}

#rabbitmq config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Logging
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

gateway.url=${GATEWAY_URL}
