spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - name: RequestRateLimiter
                  args:
                      redis-rate-limiter.replenishRate: 100 # tokens/second
                      redis-rate-limiter.burstCapacity: 200 # max tokens
                      key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                      name: defaultCircuitBreaker
                      fallbackUri: forward:/fallback
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    "[/**]":
                        allowedOrigins:
                            - "http://localhost:3000"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                            - PATCH
                        allowedHeaders:
                            - Content-Type
                            - Authorization
                            - X-Requested-With
                            - Refresh-Token
                        allowCredentials: true
                        maxAge: 3600
            discovery:
                locator:
                    enabled: true
                    #lower-case-service-id: true
            routes:
                #eureka
                - id: eureka
                  uri: ${EUREKA_SERVER_URI}
                  predicates:
                      - Path=/eureka/web
                  filters:
                      - SetPath=/
                - id: eureka-static
                  uri: ${EUREKA_SERVER_URI}
                  predicates:
                      - Path=/eureka/**
                # dashboard-service
                - id: dashboard-service-dashboard
                  uri: lb://dashboard-service
                  predicates:
                      - Path=/api/dashboard/**
                - id: dashboard-service-merchant-dashboard
                  uri: lb://dashboard-service
                  predicates:
                      - Path=/api/merchant/dashboard/**
                - id: dashboard-service-user-admin-stats
                  uri: lb://dashboard-service
                  predicates:
                      - Path=/api/dashboard/users/admin/stats/**
                - id: dashboard-service-restaurant-admin-stats
                  uri: lb://dashboard-service
                  predicates:
                      - Path=/api/dashboard/restaurants/admin/stats
                #user-service
                - id: user-service
                  uri: lb://user-service
                  predicates:
                      - Path=/api/users/**
                - id: user-service-docs
                  uri: lb://user-service
                  predicates:
                      - Path=/v3/api-docs/user-service
                # Chat-service
                - id: chat-service-api
                  uri: lb://chat-service
                  predicates:
                      - Path=/api/chat/**
                - id: chat-service-docs
                  uri: lb://chat-service
                  predicates:
                      - Path=/v3/api-docs/chat-service
                - id: chat-service-websocket
                  uri: lb:ws://chat-service
                  predicates:
                      - Path=/ws/**
                # SSE connection (notification-service)
                - id: sse-connection
                  uri: lb://notification-service
                  predicates:
                      - Path=/api/sse/subscribe/**
                      - Method=GET
                # recommendation-service
                - id: recommendation-service
                  uri: lb://recommendation-service
                  predicates:
                      - Path=/api/recommendations/**
                - id: recommendation-service-docs
                  uri: lb://recommendation-service
                  predicates:
                      - Path=/v3/api-docs/recommendation-service
                # restaurant-service
                - id: restaurant-service
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/restaurant/**
                - id: restaurant-service-cate
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/category/**
                - id: restaurant-service-product
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/products/**
                - id: restaurant-service-productsize
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/productsize/**
                - id: restaurant-service-review
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/review/**
                - id: restaurant-service-size
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/api/size/**
                - id: restaurant-service-docs
                  uri: lb://restaurant-service
                  predicates:
                      - Path=/v3/api-docs/restaurant-service
                # payment-service
                - id: payment-service
                  uri: lb://payment-service
                  predicates:
                      - Path=/api/payments/**
                - id: payment-service-webhook
                  uri: lb://payment-service
                  predicates:
                      - Path=/payment/payos-webhook
                - id: payment-service-docs
                  uri: lb://payment-service
                  predicates:
                      - Path=/v3/api-docs/payment-service
                # order-service
                - id: order-service
                  uri: lb://order-service
                  predicates:
                      - Path=/api/order/**
                - id: cart-service
                  uri: lb://order-service
                  predicates:
                      - Path=/api/cart/**
                - id: order-service-docs
                  uri: lb://order-service
                  predicates:
                      - Path=/v3/api-docs/order-service
                # blog-service
                - id: blog-service
                  uri: lb://blog-service
                  predicates:
                      - Path=/api/blogs/**
                - id: blog-service-docs
                  uri: lb://blog-service
                  predicates:
                      - Path=/v3/api-docs/blog-service
                - id: dashboard-service-docs
                  uri: lb://dashboard-service
                  predicates:
                      - Path=/v3/api-docs/dashboard-service

eureka:
    instance:
        #hostname: ${spring.application.name}
        #prefer-ip-address: false
        #instance-id: ${spring.application.name}:${random.value}

    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}

logging:
    level:
        root: TRACE

#Swagger
springdoc:
    swagger-ui:
        path: /api-docs/swagger-ui.html
        urls:
            - name: User Service
              url: /v3/api-docs/user-service
            - name: Chat Service
              url: /v3/api-docs/chat-service
            - name: Recommendation Service
              url: /v3/api-docs/recommendation-service
            - name: Dashboard Service
              url: /v3/api-docs/dashboard-service
            - name: Restaurant Service
              url: /v3/api-docs/restaurant-service
            - name: Payment Service
              url: /v3/api-docs/payment-service
            - name: Blog Service
              url: /v3/api-docs/blog-service
            - name: Order Service
              url: /v3/api-docs/order-service

# resilience4j config (circuit breaker)
resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10 # Theo dõi 10 request gần nhất
                permittedNumberOfCallsInHalfOpenState: 3 # Cho phép 3 request thử khi đang Half-Open
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 5 # Tối thiểu 5 request mới bắt đầu tính toán
                waitDurationInOpenState: 4s # Chờ 4s trước khi thử mở lại mạch (Half-Open)
                failureRateThreshold: 50 # Nếu 50% request bị lỗi -> Ngắt mạch
                eventConsumerBufferSize: 10
                slowCallRateThreshold: 60 # % slow calls -> open
                slowCallDurationThreshold: 2s # Call > 3s = slow
                automaticTransitionFromOpenToHalfOpenEnabled: true # Tự động chuyển từ OPEN sang HALF_OPEN
                recordExceptions:
                    - java.io.IOException
                    - java.util.concurrent.TimeoutException
                    # 5xx từ downstream service
                    - org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError
                    - org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway
                    - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
                    - org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout

                ignoreExceptions:
                    - org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
                    - org.springframework.web.reactive.function.client.WebClientResponseException$Unauthorized
                    - org.springframework.web.reactive.function.client.WebClientResponseException$Forbidden
                    - org.springframework.web.reactive.function.client.WebClientResponseException$NotFound
                    - org.springframework.web.reactive.function.client.WebClientResponseException$UnprocessableEntity
                    - org.springframework.web.reactive.function.client.WebClientResponseException$TooManyRequests

    timelimiter:
        configs:
            default:
                timeoutDuration: 3s # service response > 3s thì xem là timeout
                cancelRunningFuture: true

    retry:
        configs:
            default:
                maxAttempts: 3
                waitDuration: 1s
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                retryExceptions:
                    - java.io.IOException
                    - java.net.ConnectException
                    - org.springframework.web.reactive.function.client.WebClientRequestException
                ignoreExceptions:
                    - org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
                    - org.springframework.web.reactive.function.client.WebClientResponseException$NotFound
                    - org.springframework.web.reactive.function.client.WebClientResponseException$Unauthorized
