spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - name: RequestRateLimiter
                  args:
                      redis-rate-limiter.replenishRate: 100 # tokens/second
                      redis-rate-limiter.burstCapacity: 200 # max tokens
                      key-resolver: '#{@ipKeyResolver}'
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowedOrigins:
                            - 'http://localhost:3000'
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                            - PATCH
                        allowedHeaders:
                            - Content-Type
                            - Authorization
                            - X-Requested-With
                            - Refresh-Token
                        allowCredentials: true
                        maxAge: 3600
            discovery:
                locator:
                    enabled: true
                    #lower-case-service-id: true
            routes:

eureka:
    instance:
        #hostname: ${spring.application.name}
        #prefer-ip-address: false
        #instance-id: ${spring.application.name}:${random.value}
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}

logging:
    level:
        root: TRACE

#Swagger
springdoc:
    swagger-ui:
        path: /api-docs/swagger-ui.html
        urls:
