spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - name: RequestRateLimiter
                  args:
                      redis-rate-limiter.replenishRate: 100 # tokens/second
                      redis-rate-limiter.burstCapacity: 200 # max tokens
                      key-resolver: '#{@ipKeyResolver}'
                - name: CircuitBreaker
                  args:
                      name: defaultCircuitBreaker
                      fallbackUri: forward:/fallback
            globalcors:
                add-to-simple-url-handler-mapping: true
                cors-configurations:
                    '[/**]':
                        allowedOrigins:
                            - 'http://localhost:3000'
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                            - PATCH
                        allowedHeaders:
                            - Content-Type
                            - Authorization
                            - X-Requested-With
                            - Refresh-Token
                        allowCredentials: true
                        maxAge: 3600
            discovery:
                locator:
                    enabled: true
                    #lower-case-service-id: true
            routes:
                #eureka
                - id: eureka
                  uri: ${EUREKA_SERVER_URI}
                  predicates:
                      - Path=/eureka/web
                  filters:
                      - SetPath=/
                - id: eureka-static
                  uri: ${EUREKA_SERVER_URI}
                  predicates:
                      - Path=/eureka/**
                #user-service
                - id: user-service
                  uri: lb://user-service
                  predicates:
                      - Path=/api/users/**
                      - Method=GET
                  filters:
                      - name: JwtAuthentication
                - id: user-service-put
                  uri: lb://user-service
                  predicates:
                      - Path=/api/users/*
                      - Method=PUT
                  filters:
                      - name: JwtAuthentication
                - id: oauth2-authorization
                  uri: lb://user-service
                  predicates:
                      - Path=/oauth2/authorization/**
                - id: oauth2-callback
                  uri: lb://user-service
                  predicates:
                      - Path=/login/oauth2/code/**
                - id: user-service-docs
                  uri: lb://user-service
                  predicates:
                      - Path=/v3/api-docs/user-service
                                # restaurant-service
                                - id: restaurant-service
                                    uri: lb://restaurant-service
                                    predicates:
                                            - Path=/api/restaurants/**
                                    filters:
                                            - name: JwtAuthentication
                                - id: restaurant-service-docs
                                    uri: lb://restaurant-service
                                    predicates:
                                            - Path=/v3/api-docs/restaurant-service
                # Chat-service
                - id: chat-service-api
                  uri: lb://chat-service
                  predicates:
                      - Path=/api/chat/roomId/**, /api/chat/rooms/**
                  filters:
                      - name: JwtAuthentication
                - id: chat-service-websocket
                  uri: lb:ws://chat-service
                  predicates:
                      - Path=/ws/**
                  filters:
                      - name: JwtAuthentication
                # SSE connection (notification-service)
                - id: sse-connection
                  uri: lb://notification-service
                  predicates:
                      - Path=/api/sse/subcribe/**
                      - Method=GET

eureka:
    instance:
        #hostname: ${spring.application.name}
        #prefer-ip-address: false
        #instance-id: ${spring.application.name}:${random.value}
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}

logging:
    level:
        root: TRACE

