# Resilience4j Circuit Breaker Configuration

resilience4j.circuitbreaker.instances.catalogService.sliding-window-size=10
resilience4j.circuitbreaker.instances.catalogService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.catalogService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.catalogService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.catalogService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.catalogService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.reviewService.sliding-window-size=10
resilience4j.circuitbreaker.instances.reviewService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.reviewService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.reviewService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.reviewService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.reviewService.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.imageService.sliding-window-size=10
resilience4j.circuitbreaker.instances.imageService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.imageService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.imageService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.imageService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.imageService.failure-rate-threshold=50
