spring.application.name=restaurant-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/restaurant-service
springdoc.swagger-ui.enabled=false
springdoc.info.title=Restaurant Service API
springdoc.info.description=API documentation for Restaurant Service
springdoc.info.version=1.0.0
springdoc.info.contact.name=Huy

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

# Actuator with prometheus
management.metrics.export.prometheus.enabled=true

spring.datasource.url=${RESTAURANT_SERVICE_DB_URL}
spring.datasource.username=${RESTAURANT_SERVICE_DB_USER}
spring.datasource.password=${RESTAURANT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#rabbitmq config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
