spring.application.name=restaurant-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/restaurant-service
springdoc.swagger-ui.enabled=false
springdoc.info.title=Restaurant Service API
springdoc.info.description=API documentation for Restaurant Service
springdoc.info.version=1.0.0
springdoc.info.contact.name=Huy

spring.config.import=optional:file:.env[.properties]

server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.instance.hostname=${spring.application.name}
#eureka.instance.prefer-ip-address=false
#eureka.instance.instance-id=${spring.application.name}:${random.value}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${RESTAURANT_SERVICE_DB_URL}
spring.datasource.username=${RESTAURANT_SERVICE_DB_USER}
spring.datasource.password=${RESTAURANT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#OpenRouteService
openrouteservice.api-key=${OPENROUTESERVICE_API_KEY}
openrouteservice.list-url=${OPENROUTESERVICE_LIST_URL}
openrouteservice.url=${OPENROUTESERVICE_URL}


# Log để define xem có N+1 problem không
# Logging levels
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

gateway.url=${GATEWAY_URL}