spring.application.name=review-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/review-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties]


server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.instance.hostname=${spring.application.name}
#eureka.instance.prefer-ip-address=false
#eureka.instance.instance-id=${spring.application.name}:${random.value}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${REVIEW_SERVICE_DB_URL}
spring.datasource.username=${REVIEW_SERVICE_DB_USER}
spring.datasource.password=${REVIEW_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#rabbitmq config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

gateway.url=${GATEWAY_URL}
