spring.application.name=catalog-service

#Swagger
springdoc.api-docs.path=/v3/api-docs/catalog-service
springdoc.swagger-ui.enabled=false

spring.config.import=optional:file:.env[.properties]


server.port=${PORT}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
#eureka.instance.hostname=${spring.application.name}
#eureka.instance.prefer-ip-address=false
#eureka.instance.instance-id=${spring.application.name}:${random.value}

# Chỉ dùng zipkin khi deploy lên docker
management.tracing.enabled=true
# Mở tất cả các endpoint của Actuator (health, metrics, zipkin...) qua web
management.endpoints.web.exposure.include=*
#100% request sẽ được thu thập và gửi đi.
management.tracing.sampling.probability=1.0
# endpoint của zipkin server
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}

spring.datasource.url=${CATALOG_SERVICE_DB_URL}
spring.datasource.username=${CATALOG_SERVICE_DB_USER}
spring.datasource.password=${CATALOG_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#redis config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL:false}

gateway.url=${GATEWAY_URL}
